Repository vital-software/vitalizer, pull requests merged in 2018-03, with the labels that each got.

#71 Move the build to Buildkite
  .buildkite/pipeline.yml
  .dockerignore
  .npmignore
  Dockerfile
  docker-compose.buildkite.yml
  docker-compose.yml
  package.json
  test/task/e2e-simple.sh
  yarn.lock
Labels: stage: review

#78 Eslint jest upgrade
  package.json
  yarn.lock
Labels: stage: review, type: enhancement

#82 Webpack build speed and test
  .gitignore
  package.json
  test/perf/webpack.speed.bench.json
  test/public/index.css
  test/public/index.html
  test/public/index.js
  test/task/e2e-simple.sh
  webpack.config.babel.js
  yarn.lock
Labels: process: ci, stage: review, type: performance, type: testing

#83 Move webpack plugin to main deps
  package.json
  yarn.lock
Labels: stage: review, type: bug

#81 Production source maps & Webpack 4
  .gitignore
  helper/paths.js
  package.json
  script/build.js
  script/start.js
  test/app/base-component.jsx
  test/app/index.js
  test/package.json
  test/public/images/logo.svg
  test/static/images/logo.svg
  test/stub/images/logo.svg
  test/stub/index.css
  test/stub/index.js
  test/task/e2e-simple.sh
  test/yarn.lock
  webpack.config.babel.js
  yarn.lock
Labels: stage: review, type: bug, type: enhancement

#87 Fix source maps for sentry.
  webpack.config.babel.js
Labels: stage: review

#88 fix(source maps): Appends source maps to js files.
  test/stub/index.css
  test/stub/index.js
  webpack.config.babel.js
Labels: stage: review

#89 fix(Sourcemap dir): Switched back to generating sourcemaps next to th…
  helper/paths.js
  script/build.js
  test/stub/index.css
  test/stub/index.js
  test/task/e2e-simple.sh
  webpack.config.babel.js
Labels: stage: review

#92 feat(Babel minification): Switch back to new upgraded babel minifier. Resolves #90
  package.json
  webpack.config.babel.js
  yarn.lock
Labels: stage: review, type: bug

#95 Turn off mangle for minify plugin.
  webpack.config.babel.js
Labels: stage: review
