Repository vital-software/vitalizer, pull requests merged in 2018-02, with the labels that each got.

#60 Fix SSE buffering: don't use compression in the dev server
  webpack.config.babel.js
Labels: bug, review

#61 Bring master up to speed with latest NPM package
  package.json
  webpack.config.babel.js
Labels: review

#67 Add Webpack tests
  test/app/duck/question.js
  test/app/graphql/fragment/node.graphql
  test/app/graphql/question-save.graphql
  test/app/index.js
  test/public/index.js
  test/stub/index.js
  test/task/e2e-simple.sh
Labels: ci/cd pipeline, review

#68 Upgrade webpack
  package.json
  test/public/index.js
  yarn.lock
Labels: review

#69 Upgrade postcss dependencies
  package.json
  test/task/e2e-simple.sh
  yarn.lock
Labels: review

#70 feat(cypress): linting support
  .eslintrc.json
  package.json
  yarn.lock
Labels: stage: review
